export const dealData = [
  {
    tenant: "Starbucks Coffee",
    requirementSize: "1,500 – 2,000 sf",
    totalSize: "1,800 sf",
    asset: "Downtown Plaza",
    stage: "Legal",
    ner: "CA$45.00",
    contact: "Sarah Johnson",
    comment: "Drive-thru location, high traffic area",
    lastUpdated: "12/15/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "TD Bank",
    requirementSize: "2,500 – 3,000 sf",
    totalSize: "2,800 sf",
    asset: "Metro Center",
    stage: "LOI",
    ner: "CA$38.50",
    contact: "Michael Chen",
    comment: "Full-service branch with ATM vestibule",
    lastUpdated: "12/10/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "Shoppers Drug Mart",
    requirementSize: "8,000 – 10,000 sf",
    totalSize: "9,200 sf",
    asset: "Westside Mall",
    stage: "Proposals",
    ner: "CA$28.75",
    contact: "Jennifer Park",
    comment: "Anchor tenant, pharmacy + retail",
    lastUpdated: "12/08/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "RBC Royal Bank",
    requirementSize: "3,000 – 3,500 sf",
    totalSize: "3,200 sf",
    asset: "Financial District Tower",
    stage: "Touring",
    ner: "CA$52.00",
    contact: "David Rodriguez",
    comment: "Premium location, ground floor",
    lastUpdated: "12/12/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "Tim Hortons",
    requirementSize: "1,200 – 1,500 sf",
    totalSize: "1,350 sf",
    asset: "Highway 401 Plaza",
    stage: "Inquiries",
    ner: "CA$32.00",
    contact: "Lisa Thompson",
    comment: "24/7 operation, truck stop access",
    lastUpdated: "12/05/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "Walmart Supercenter",
    requirementSize: "120,000 – 140,000 sf",
    totalSize: "135,000 sf",
    asset: "Suburban Power Center",
    stage: "Legal",
    ner: "CA$18.25",
    contact: "Robert Wilson",
    comment: "New market entry, full grocery",
    lastUpdated: "12/14/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "Canadian Tire",
    requirementSize: "25,000 – 30,000 sf",
    totalSize: "28,500 sf",
    asset: "Eastside Retail Park",
    stage: "Proposals",
    ner: "CA$22.50",
    contact: "Amanda Foster",
    comment: "Auto service center included",
    lastUpdated: "12/07/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "Loblaw Companies",
    requirementSize: "35,000 – 40,000 sf",
    totalSize: "38,000 sf",
    asset: "Neighborhood Center",
    stage: "LOI",
    ner: "CA$24.75",
    contact: "Kevin O'Brien",
    comment: "No Frills banner, value-focused",
    lastUpdated: "12/11/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "McDonald's",
    requirementSize: "2,500 – 3,000 sf",
    totalSize: "2,750 sf",
    asset: "University District",
    stage: "Touring",
    ner: "CA$40.00",
    contact: "Rachel Green",
    comment: "Student population, delivery hub",
    lastUpdated: "12/09/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "Home Depot",
    requirementSize: "80,000 – 100,000 sf",
    totalSize: "95,000 sf",
    asset: "Industrial Business Park",
    stage: "Inquiries",
    ner: "CA$16.80",
    contact: "Thomas Anderson",
    comment: "Garden center, lumber yard",
    lastUpdated: "12/06/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "PetSmart",
    requirementSize: "12,000 – 15,000 sf",
    totalSize: "13,800 sf",
    asset: "Pet Lovers Plaza",
    stage: "Legal",
    ner: "CA$26.50",
    contact: "Michelle Davis",
    comment: "Grooming salon, vet clinic space",
    lastUpdated: "12/13/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "Best Buy",
    requirementSize: "20,000 – 25,000 sf",
    totalSize: "22,500 sf",
    asset: "Tech Hub Mall",
    stage: "Dead Deals",
    ner: "CA$30.25",
    contact: "James Miller",
    comment: "Market exit, online shift",
    lastUpdated: "11/28/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "Subway",
    requirementSize: "800 – 1,200 sf",
    totalSize: "1,100 sf",
    asset: "Hospital Food Court",
    stage: "Leases Executed",
    ner: "CA$35.00",
    contact: "Patricia Lee",
    comment: "Healthcare workers, visitors",
    lastUpdated: "12/01/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "GoodLife Fitness",
    requirementSize: "15,000 – 20,000 sf",
    totalSize: "18,500 sf",
    asset: "Fitness Center Complex",
    stage: "Leases Out",
    ner: "CA$20.75",
    contact: "Christopher Brown",
    comment: "24-hour access, pool facility",
    lastUpdated: "12/03/24",
    link: "/vts/lease/deals/profile",
  },
  {
    tenant: "Dollarama",
    requirementSize: "8,000 – 10,000 sf",
    totalSize: "9,500 sf",
    asset: "Value Village Plaza",
    stage: "Proposals",
    ner: "CA$18.50",
    contact: "Stephanie White",
    comment: "Dollar store format, high volume",
    lastUpdated: "12/04/24",
    link: "/vts/lease/deals/profile",
  },
];

export const pipelineData = [
  { label: "Inquiries", value: 12 },
  { label: "Touring", value: 7 },
  { label: "Proposals", value: 5 },
  { label: "LOI", value: 5 },
  { label: "Legal", value: 2 },
  { label: "Lease Out", value: 2 },
  { label: "Executed", value: 1 },
  { label: "Dead", value: 8 },
];

export const lastUpdatedData = [
  { label: "< 30 days", value: 12 },
  { label: "30 - 60 days", value: 2 },
  { label: "60 - 90 days", value: 6 },
  { label: "90+ days", value: 3 },
];
